# Convenience makefile

DEBUG?=ON
TARGET=build
SDK=sdk

BUILD_DYNAMIC?=OFF
BUILD_TESTS?=ON
BUILD_EXAMPLES?=ON
BUILD_TYPE?=Debug

GLFW_OPTIONS=-DGLFW_USE_EGL=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF

BAKGE_OPTIONS=-DBAKGE_SDK_PATH=$(SDK) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -DBAKGE_BUILD_TESTS=$(BUILD_TESTS) -DBAKGE_BUILD_EXAMPLES=$(BUILD_EXAMPLES) -DBUILD_SHARED_LIBS=$(BUILD_DYNAMIC)

# All options
OPTIONS=$(GLFW_OPTIONS) $(BAKGE_OPTIONS)

all:
	@mkdir $(TARGET) && cd $(TARGET) && cmake .. -G "Unix Makefiles" $(OPTIONS) && make -s;

codeblocks:
	@mkdir $(TARGET) && cd $(TARGET) && cmake .. -G "CodeBlocks - Unix Makefiles" $(OPTIONS);

clean:
	rm -rf $(TARGET) $(SDK);

